name: Build Aseprite (Windows Release GUI)

on:
  push:
    branches:
      - main # Trigger on pushes to your main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [RelWithDebInfo]
        ui: [gui]
        scripting: [lua]

    steps:
    - name: Checkout Aseprite Source
      uses: actions/checkout@v4
      with:
        # ************************************************************
        # * THIS IS THE CRITICAL LINE THAT MUST BE YOUR REPO *
        # ************************************************************
        repository: Reec-3/aseprite
        ref: main # Assumes 'main' is the default branch of your fork
        submodules: 'recursive'

    - name: Install Dependencies
      if: runner.os == 'Linux' # This step will be skipped on Windows

    - name: Install Skia
      if: ${{ matrix.ui == 'gui' }}
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          this_dir=$(cygpath "${{ github.workspace }}")
        else
          this_dir="${{ github.workspace }}"
        fi
        skia_url=$(source $this_dir/laf/misc/skia-url.sh | xargs)
        skia_file=$(basename $skia_url)
        curl --ssl-revoke-best-effort -L -o "$skia_file" "$skia_url"
        unzip -o "$skia_file" -d skia

    - name: ccache
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }} # Skipped on Windows
      uses: hendrikmuhs/ccache-action@v1.2.17
      with:
        key: ${{ matrix.os }}-${{ matrix.ui }}-${{ matrix.scripting }}-${{ matrix.build_type }}

    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows' # Only runs on Windows

    - name: Generating Makefiles
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          export enable_ccache=off
        else
          export enable_ccache=on
        fi
        export laf_backend=${{ matrix.ui == 'gui' && 'skia' || 'none' }}
        export enable_scripting=${{ matrix.scripting == 'lua' && 'on' || 'off' }}
        export skia_arch=x64

        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DENABLE_TESTS=OFF \
          -DENABLE_SCRIPTING=$enable_scripting \
          -DENABLE_CCACHE=$enable_ccache \
          -DLAF_BACKEND=$laf_backend \
          -DSKIA_DIR=$(realpath skia) \
          -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-$skia_arch)

    - name: Compiling
      shell: bash
      run: |
        cd build && ninja

    - name: Prepare Aseprite Application for Artifact
      run: |
        mkdir -p aseprite-build
        $exe_path = "build/bin/aseprite.exe"

        if (Test-Path $exe_path) {
          Copy-Item $exe_path -Destination "aseprite-build/"
          Write-Host "Copied aseprite.exe to artifact directory."
        } else {
          Write-Host "Aseprite executable not found at $exe_path. Listing build directory for debugging:"
          Get-ChildItem -Path "build" -Recurse
          exit 1
        }

        if (Test-Path "data") {
          Copy-Item -Path "data" -Destination "aseprite-build/data" -Recurse
          Write-Host "Copied 'data' folder to artifact directory."
        } else {
          Write-Host "Aseprite 'data' folder not found at source root."
        }
        Write-Host "Contents of aseprite-build directory:"
        Get-ChildItem -Path "aseprite-build" -Recurse
      shell: pwsh

    - name: Upload Aseprite Build as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-windows-gui-relwithdebinfo-${{ github.sha }}
        path: aseprite-build/
        retention-days: 7
        if-no-files-found: error
